version: "3.9"
services:
  php:
    container_name: php_Service
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
      target: base
    ports:
      - "8080:80"
    volumes:
      - ./app/src:/var/www/html
